name: Deploy to ECR

on: 
  push:
    branches: [ master ]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: us-east-1

    - name: Build, tag, and push Docker image
      run: |
        ECR_REGISTRY_URL="${{ secrets.ECR_REGISTRY_URL }}"
        IMAGE_TAG="v2" # Set your image tag

        # Build the Docker image
        docker build -t clo835-week4:$IMAGE_TAG .

        # Tag the image with the full ECR path
        docker tag clo835-week4:$IMAGE_TAG $ECR_REGISTRY_URL/clo835-week4:$IMAGE_TAG

        # Push the image to ECR
        docker push $ECR_REGISTRY_URL/clo835-week4:$IMAGE_TAG
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # This line is optional and should only be used if you are using temporary credentials
