name: Deploy to ECR

on: 
  push:
    branches: [ master ]

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image
      run: |
        # Define the ECR Registry URL from the secret and the repository name
        ECR_REGISTRY_URL="${{ secrets.ECR_REGISTRY_URL }}"
        REPO_NAME="clo835-week4"
        IMAGE_TAG="v2" # Set your image tag

        # Navigate to your Dockerfile directory if it's not in the root
        # cd path/to/your/dockerfile/

        # Build the Docker image
        docker build -t $REPO_NAME:$IMAGE_TAG .

        # Tag the image with the full ECR path
        docker tag $REPO_NAME:$IMAGE_TAG $ECR_REGISTRY_URL/$REPO_NAME:$IMAGE_TAG

        # Push the image to ECR
        docker push $ECR_REGISTRY_URL/$REPO_NAME:$IMAGE_TAG
